# ---------------- khaaliSplit ---------------------------------------------------- #

.PHONY: dev prod

dev:
	@echo "Starting dev server..."
	@echo "TODO: Add your dev server command here"

prod:
	@echo "Starting prod server..."
	@echo "TODO: Add your prod server command here"
