# Generated by Django 6.0.2 on 2026-02-07 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurntAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('original_subname', models.CharField(max_length=100)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('burnt_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('subname', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('reputation_score', models.IntegerField(default=50)),
                ('farcaster_fid', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('expense_added', 'Expense added'), ('expense_updated', 'Expense updated'), ('settlement_initiated', 'Settlement initiated'), ('settlement_confirmed', 'Settlement confirmed'), ('settlement_failed', 'Settlement failed'), ('friend_request', 'Friend request sent'), ('friend_accepted', 'Friend request accepted'), ('friend_removed', 'Friend removed'), ('group_created', 'Group created'), ('group_invite', 'Group invitation'), ('group_joined', 'Joined group'), ('group_left', 'Left group'), ('wallet_linked', 'Wallet linked'), ('pubkey_registered', 'Public key registered')], max_length=50)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('expense_id', models.IntegerField(blank=True, null=True)),
                ('settlement_hash', models.CharField(blank=True, default='', max_length=66)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True, default='')),
                ('is_synced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CachedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('name_hash', models.CharField(blank=True, default='', max_length=66)),
                ('member_count', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CachedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.IntegerField(unique=True)),
                ('creator_address', models.CharField(max_length=42)),
                ('data_hash', models.CharField(blank=True, default='', max_length=66)),
                ('encrypted_data', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact amounts'), ('percentage', 'Percentage')], default='equal', max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('participants_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.cachedgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CachedSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('token', models.CharField(default='usdc', max_length=10)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source_chain', models.IntegerField()),
                ('dest_chain', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('bridging', 'Bridging'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_settlements', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='api.cachedgroup')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CachedFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_address', models.CharField(max_length=42)),
                ('status', models.CharField(choices=[('pending_sent', 'Pending (sent)'), ('pending_received', 'Pending (received)'), ('accepted', 'Accepted'), ('removed', 'Removed')], default='pending_sent', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cached_friend_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_friends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'friend_address')},
            },
        ),
        migrations.CreateModel(
            name='CachedGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_address', models.CharField(max_length=42)),
                ('encrypted_key', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('left', 'Left')], default='invited', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.cachedgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LinkedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('is_primary', models.BooleanField(default=False)),
                ('chain_id', models.IntegerField(default=11155111)),
                ('token', models.CharField(default='usdc', max_length=10)),
                ('token_addr', models.CharField(blank=True, default='', max_length=42)),
                ('pub_key', models.CharField(blank=True, default='', max_length=130)),
                ('pub_key_registered', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'address')},
            },
        ),
    ]
